soc: renesas: Provide dummy rcar_rst_read_mode_pins() for compile-testing
If the R-Car RST driver is not included, compile-testing R-Car clock
drivers fails with a link error:

    undefined reference to `rcar_rst_read_mode_pins'

To fix this, provide a dummy version.  Use the exact same test logic as
in drivers/soc/renesas/Makefile, as there is no Kconfig symbol (yet) to
control compilation of the R-Car RST driver.

Fixes: 527c02f66d263d2e ("soc: renesas: Add R-Car RST driver")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
---
This isn't an issue now, but it does prevent enabling compile-testing of
the R-Car clock drivers.  As this is a dependency between two different
subsystems, I think this patch should be fast-tracked.

The #ifdef condition will be revised later, when the R-Car RST driver
gains its own Kconfig symbol.

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>