clk: renesas: cpg-mssr: Use of_node_get_match_data() helper
If CONFIG_OF=n:

    drivers/clk/renesas/renesas-cpg-mssr.c: In function ‘cpg_mssr_probe’:
    drivers/clk/renesas/renesas-cpg-mssr.c:673: warning: dereferencing ‘void *’ pointer
    drivers/clk/renesas/renesas-cpg-mssr.c:673: error: request for member ‘data’ in something not a structure or union

To fix this, use the of_node_get_match_data() helper, for which a dummy
version is provided if CONFIG_OF=n.

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
---
This depends on "of: Introduce of_node_get_match_data() helper".